package com.constants;

public interface HardCodedSQL {
	
	public static final String DELETE_TOURISTSPOT_SQL="DELETE FROM TOURISTSPOT";

	public static final String DELETE_PACKASSOCIATION_SQL="DELETE FROM PACK_ASSOCIATION";

	public static final String DELETE_TOURPACK_SQL="DELETE FROM TOURISTPACK";

	public static final String DELETE_HOTELS_SQL="DELETE FROM HOTEL";

	public static final String DELETE_HOTEL_WHERE_HOTELID_SQL="DELETE FROM HOTEL WHERE HOTELID=?";

	public static final String DELETE_TOUR_WHERE_PACKID_SQL="DELETE FROM TOURISTSPOT WHERE SPOTID=?";

	public static final String DELETE_TOURPACK_WHERE_PACKID_SQL="DELETE FROM TOURISTPACK WHERE PACKID=?";

	public static final String INSERT_HOTEL_SQL="INSERT INTO HOTEL(HOTELNAME,HOTELDESC,HOTELRENT,HOTELIMAGELOC)VALUES(?,?,?,?)";

public static final String	INSERT_NEGATIVEKEYWORDS_SQL="INSERT INTO NEGATIVEKEYWORDS(NEGATIVEKEYWORD)VALUES(?)";

public static final String	INSERT_PACKASSOCIATION_SQL="INSERT INTO PACK_ASSOCIATION(TOURISTPACK_FK,HOTELPACK_FK,SPOTID_FK)VALUES(?,?,?)";

	public static final String INSERT_POSTIVEKEYWORDS_SQL="INSERT INTO POSITIVEKEYWORDS(PKEYWORDS)VALUES(?)";

	public static final String INSERT_TOURPACK_SQL="INSERT INTO TOURISTPACK(PACKNAME,PACKDESC)VALUES(?,?)"; 

	public static final String INSERT_TOURSPOT_SQL="INSERT INTO TOURISTSPOT(SPOTNAME,SPOTDESC,SPOTRENT,SPOTIMAGELOC,PLACE,STATE,COUNTRY)VALUES(?,?,?,?,?,?)";

public static final String	RETRIVE_PACKASSOCIATION_SQL="SELECT TOURISTPACK_FK,HOTELPACK_FK,SPOTID_FK FROM PACK_ASSOCIATION";

public static final String	RETRIVE_UNIQUEPACKIDS_SQL="SELECT DISTINCT TOURISTPACK_FK FROM PACK_ASSOCIATION";

public static final String	RETRIVE_ALLHOTELS_SQL="SELECT HOTELID,HOTELNAME,HOTELDESC,HOTELRENT,HOTELIMAGELOC FROM HOTEL";

public static final String	RETRIVE_TOURISTPACKS_SQL="SELECT PACKID,PACKNAME,PACKDESC FROM TOURISTPACK";

public static final String RETRIVE_TOURISTSPOT_SQL="SELECT SPOTID,SPOTNAME,SPOTDESC,SPOTRENT,SPOTIMAGELOC,PLACE,STATE,COUNTRY FROM TOURISTSPOT";

public static final String RETRIVE_PACKASSCOCIATIONMODEL_SQL="SELECT PACKASSID,TOURISTPACK_FK,HOTELPACK_FK,SPOTID_FK FROM PACK_ASSOCIATION WHERE TOURISTPACK_FK=?";

public static final String RETRIVE_HOTEL_WHERE_HOTELID_COL="SELECT HOTELID,HOTELNAME,HOTELDESC,HOTELRENT,HOTELIMAGELOC FROM HOTEL WHERE HOTELID=?";

public static final String	RETRIVE_NEGATIVEKEYWORDS_SQL="SELECT NEGATIVEKEYID,NEGATIVEKEYWORD FROM NEGATIVEKEYWORDS";

public static final String	RETRIVE_POSITIVEKEYWORDS_SQL="SELECT PKEYID,PKEYWORDS FROM POSITIVEKEYWORDS";

public static final String RETRIVE_TOURISTPACK_WHERE_TOUR_PACK_SQL="SELECT  PACKID,PACKNAME,PACKDESC FROM TOURISTPACK WHERE PACKID=?";

public static final String RETRIVE_TOURISTSPOT_WHERE_SPOTITD_SQL="SELECT SPOTID,SPOTNAME,SPOTDESC,SPOTRENT,SPOTIMAGELOC,PLACE,STATE,COUNTRY FROM TOURISTSPOT WHERE SPOTID=?";

public static final String	RETRIVE_SPOTIDS_WHERE_PACKID_SQL="SELECT SPOTID_FK FROM PACK_ASSOCIATION WHERE TOURISTPACK_FK=?";

public static final String RETRIVE_HOTELDS_WHERE_PACKID_SQL="SELECT HOTELPACK_FK FROM PACK_ASSOCIATION WHERE TOURISTPACK_FK=?";

public static final String RETRIVE_REGISTER_USERIDS_SQL="SELECT USERID FROM LOGIN";

public static final String 	INSERT_LOGIN_SQL="INSERT INTO LOGIN(FIRSTNAME,LASTNAME,PASSWORD,EMAIL,USERID)VALUES(?,?,?,?,?)";

public static final String 	RETRIVE_PASSWORD_WHERE_USERID_SQL="SELECT PASSWORD FROM LOGIN WHERE USERID=?";

public static final String	RETRIVE_LOGINTYPE_WHERE_USERID_SQL="SELECT LOGINTYPE FROM LOGIN WHERE USERID=?";

public static final String RETRIVE_COST_WHERE_SPOTID_SQL="SELECCT SPOTRENT FROM TOURISTSPOT WHERE SPOTID=?";

public static final String 	RETRIVE_ACCCOUNTNOS_SQL="SELECT ACCOUNTNO FROM BANK";

public static final String	RETRIVE_IPIN_WHERE_ACCNO_SQL="SELECT IPIN FROM BANK WHERE ACCOUNTNO=?";

public static final String	RETRIVE_BALANCE_WHERE_ACCNO_SQL="SELECT AMOUNT FROM BANK WHERE ACCOUNTNO=?";

public static final String	UPDATE_BALANCE_SQL="UPDATE BANK SET AMOUNT=? WHERE ACCOUNTNO=?";

public static final String INSERT_TRANS_SQL="INSERT INTO TRANSACTION(CUSTOMERID,PACKID)VALUES(?,?)";

public static final String DELETE_PACK_WHERE_PACKID_SQL="DELETE FROM TOURISTPACK WHERE PACKID=?";

public static final String RETRIVE_BOOKPACKS_SQL = "SELECT BOOKID,BOOKNAME,CATID,SUBCATID,AUTHOR,PUBLISHER,BOOKPRICE,BOOKOVERVIEW,EDITION,RATING,BOOKLOC FROM BOOK";


}
