package com.constants;

public interface Constants {

	interface Keys{
		String OBJ="OBJ";
		String STARTED = "STARTED";
		String FAILED = "FAILED";
		String SUCESS = "SUCESS";
	}
	
	interface Views{
		
		String ERROR_PAGE ="error";
		String SUCESS_PAGE ="sucess";
	}
	
	interface Message{
		
		String SAVE_OBJECT_REPOSITORY_SUCESS="Object Repository has been Saved Sucessfully";
		String OBJECT_REPOSITORY_ALREADY_EXIST = "Duplicate Object Repository Already Exist";
		String OBJECT_REPOSITORY_SAVE_FAILED = "Could not Save Object Repository";
		String OBJECT_REPOSITORY_UPDATE_FAILED = "Object Repository Updation has Failed";
		String OBJ_REPOSITORY_LIST_EMPTY = "Object Repository List is Empty";
		String OBJ_REPOSITORY_LIST_SUCESS = "Object Repository List Retrival is Sucessful";
		String SAVE_TEST_REPOSITORY_SUCESS = "Test Case has been Saved Sucessfully";
		String DUPLICATE_TEST_CASE_REPO = "Duplicate Test Case Already Exist";
		String TEST_REPOSITORY_SAVE_FAILED = "Test Case Could not be Saved";
		String TEST_REPOSITORY_LIST_EMPTY = "Test Repository List is Empty";
		String TEST_REPOSITORY_LIST_SUCESS = "Test Repository List is Sucessful";
		String PAGE_NAME_LIST_EMPTY = "Page Name List is Empty";
		String PAGE_NAME_REPOSITORY_LIST_SUCESS = "Page Name Repository List is Sucessful";
		String OBJ_REPO_LIST_EMPTY = "Object Repository List is Empty";
		String AUTO_COMMAND_LIST_EMPTY = "Automation Command List is Empty";
		String AUTO_COMMAND_REPOSITORY_LIST_SUCESS = "Automation Command List is Retrived";
		String SAVE_STEP_REPOSITORY_SUCESS = "Step Repository has been Sucessful";
		String DUPLICATE_STEP_REPO = "Duplicate Step No Exist";
		String STEP_REPOSITORY_SAVE_FAILED = "Step Repository could not be Saved";
		String STEP_REPOSITORY_UPDATE_FAILED = "Step Repository updation has Failed";
		String PLEASE_SELECT_STEPREPO = "Please Select Step Repository";
		String PLEASE_SELECT_ELEMENT_NAME = "Please Select Element Name";
		String PLEASE_SELECT_ELEMENT_VALUE = "Please Select Element Value";
		String PLEASE_SELECT_PAGE_NAME = "Please Provide Page Name";
		String PLEASE_SELECT_STEP_DESC = "Please Provide the Step Description";
		String PLEASE_SELECT_STEP_NO = "Please Select Step No";
		String PLEASE_SELECT_TEST_CASE_NAME = "Please Select Test Case Name";
		String STEP_REPOSITORY_LIST_EMPTY = "Step Repository List is Empty";
		String STEP_REPOSITORY_LIST_SUCESS = "Step Repository List is Sucessful";
		String EXECUTION_OF_TEST_CASES_SUCESSFUL = "Execution of Test Case is Sucessful";
		String NO_STEPS_FOUND_FOR_EXECUTION = "No Steps Found for the given Test Case";
		String SAVE_TEST_RESULTS_FALED = "Saving of Test Results have Failed";
		String SAVE_BATCH_STEP_RESULTS_FAILED = "Saving of Steps Results Failed";
		String DEL_TEST_CASE_RESULTS_FAILED = "Deletion of Test Case Results has Failed";
		String DEL_TEST_CASE_STEP__RESULTS_FAILED = "Deletion of Step Results has Failed";
		String TESTCASE_RESULTS_LIST_EMPTY = "Test Case Results List is Empty";
		String TESTCASE_RESULTS_LIST_SUCESS = "Test Case Results List is Retrived Sucessfully";
		String STEP_RESULTS_LIST_EMPTY = "Step Results List is Empty";
		String STEP_RESULTS_LIST_SUCESS = "Step Results List is Sucess";
		String TEST_CASE_DESC_EMPTY = "Test Case Description Cannot be Empty";
		String DELETE_TEST_SUCESS = "Deletion of Test Case is Sucessful";
		String DELETE_STEP_SUCESS = "Deletion of Step is Sucessful";
		String DELETE_OBJECT_REPO_SUCESS = "Deletion of Object Repository is Sucessful";
		String COULD_NOT_SAVE_COMPARISION_TIME = "Could not Save Comparision Time";
		String TIME_LIST_EMPTY = "Time List is Empty";
		String TIME_LIST_SUCESS = "Time List Retrival is Sucessful";
	}
	
	interface SQLKeys{

		String INSERT_OBJECT_REPOSITORY_INFO_SQL = "INSERT_OBJECT_REPOSITORY_INFO_SQL";
		String UPDATE_OBJECT_REPOSITORY_INFO_WHERE_PAGENAME_AND_ELEMENTNAME_SQL = "UPDATE_OBJECT_REPOSITORY_INFO_WHERE_PAGENAME_AND_ELEMENTNAME_SQL";
		String SELECT_OBJECT_REPO_FOR_PAGENAME_AND_ELEMENTNAME_SQL = "SELECT_OBJECT_REPO_FOR_PAGENAME_AND_ELEMENTNAME_SQL";
		String SELECT_OBJECT_REPO_ALL_SQL = "SELECT_OBJECT_REPO_ALL_SQL";
		String SELECT_TEST_REPO_FOR_TESTNAME_SQL = "SELECT_TEST_REPO_FOR_TESTNAME_SQL";
		String INSERT_TEST_REPOSITORY_INFO_SQL = "INSERT_TEST_REPOSITORY_INFO_SQL";
		String SELECT_TEST_REPO_ALL_SQL = "SELECT_TEST_REPO_ALL_SQL";
		String SELECT_PAGE_NAME_REPO_ALL_SQL = "SELECT_PAGE_NAME_REPO_ALL_SQL";
		String SELECT_OBJECT_REPO_ALL_FOR_PAGE_NAME_SQL = "SELECT_OBJECT_REPO_ALL_FOR_PAGE_NAME_SQL";
		String SELECT_AUTOMATION_FOR_ACTION_TYPE_SQL = "SELECT_AUTOMATION_FOR_ACTION_TYPE_SQL";
		String SELECT_STEP_REPO_FOR_STEP_NO_AND_TESTCASENAME_SQL = "SELECT_STEP_REPO_FOR_STEP_NO_AND_TESTCASENAME_SQL";
		String INSERT_STEP_REPOSITORY_INFO_SQL = "INSERT_STEP_REPOSITORY_INFO_SQL";
		String UPDATE_STEP_REPOSITORY_INFO_WHERE_TESTCASENAME_AND_STEPNO_SQL = "UPDATE_STEP_REPOSITORY_INFO_WHERE_TESTCASENAME_AND_STEPNO_SQL";
		String SELECT_STEP_REPO_ALL_FOR_TEST_CASE_NAME_SQL = "SELECT_STEP_REPO_ALL_FOR_TEST_CASE_NAME_SQL";
		String SELECT_STEP_REPO_ALL_FOR_TEST_CASE_NAME_ORDER_BY_STEP_NO_SQL = "SELECT_STEP_REPO_ALL_FOR_TEST_CASE_NAME_ORDER_BY_STEP_NO_SQL";
		String INSERT_TEST_CASE_RESULTS_SQL = "INSERT_TEST_CASE_RESULTS_SQL";
		String INSERT_STEPRESULTS_NAMED_SQL = "INSERT_STEPRESULTS_NAMED_SQL";
		String INSERT_BATCH_STEP_RESULTS_INFO_SQL = "INSERT_BATCH_STEP_RESULTS_INFO_SQL";
		String DELETE_TESTCASERESULTS_WHERE_TESTCASENAME_SQL = "DELETE_TESTCASERESULTS_WHERE_TESTCASENAME_SQL";
		String DELETE_STEPRESULTS_WHERE_TESTCASENAME_SQL = "DELETE_STEPRESULTS_WHERE_TESTCASENAME_SQL";
		String SELECT_AUTOMATION_FOR_ELEMENT_TYPE_SQL = "SELECT_AUTOMATION_FOR_ELEMENT_TYPE_SQL";
		String SELECT_TEST_CASE_RESULTS_FOR_TEST_NAME_SQL = "SELECT_TEST_CASE_RESULTS_FOR_TEST_NAME_SQL";
		String SELECT_TEST_STEP_RESULTS_FOR_TEST_NAME_SQL = "SELECT_TEST_STEP_RESULTS_FOR_TEST_NAME_SQL";
		String SELECT_TESTCASEDESC_FOR_TESTCASE_NAME_SQL = "SELECT_TESTCASEDESC_FOR_TESTCASE_NAME_SQL";
		String DELETE_TESTCASE_WHERE_TESTCASENAME_SQL = "DELETE_TESTCASE_WHERE_TESTCASENAME_SQL";
		String DELETE_STEP_FROM_TESTCASE_WHERE_TESTCASENAME_AND_STEPNO_SQL = "DELETE_STEP_FROM_TESTCASE_WHERE_TESTCASENAME_AND_STEPNO_SQL";
		String DELETE_OBJECTREPO_FROM_OBJECTREPO_WHERE_PAGENAME_AND_ELEMENTNAME_SQL = "DELETE_OBJECTREPO_FROM_OBJECTREPO_WHERE_PAGENAME_AND_ELEMENTNAME_SQL";
		String INSERT_TIME_COMPARISION_INFO_SQL = "INSERT_TIME_COMPARISION_INFO_SQL";
		String SELECT_TIME_COMPARSION_ALL_SQL = "SELECT_TIME_COMPARSION_ALL_SQL";
		 
	}
	
	
	interface AUTOMATIONACTIONS{

		String LOADURL = "LOADURL";
		String SENDKEYS = "SENDKEYS";
		String BUTTONCLICK = "BUTTONCLICK";
		String DELAY = "DELAY";
		String LINKCLICK = "LINKCLICK";
		String HTMLTEXTVIEW = "HTMLTEXTVIEW";
		
		String CLICKLINK="CLICKLINK";
		
		
	}
	
	interface AUTOMATIONIDENTIFICATION{

		String LOADURL = "LOADURL";
		String SENDKEYS = "SENDKEYS";
		String NAME = "Name";
		String ID = "Id";
		String XPATH = "Xpath";
		
		
	}
	
	
}
